=== AliFathy-1999/ITI-Tasks/XML Tasks/AliAhmed_XML_Lab1/src/main/java/aliahmed_xml_lab1/libraryDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->

<!ELEMENT library (info+, books*)>
<!ELEMENT info (location*, description?,librarian+)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT librarian (#PCDATA)>

<!ELEMENT books (Btitle?, ISBN?,Author+,preface?,parts+)>
<!ELEMENT Btitle (#PCDATA)>
<!ATTLIST Btitle bid ID #REQUIRED>
<!ELEMENT ISBN (#PCDATA)>
<!ATTLIST ISBN id ID #REQUIRED>
<!ELEMENT Author (#PCDATA)>
<!ATTLIST Author gender ( Male | Female ) "Male">
<!ELEMENT preface (#PCDATA)>

<!ELEMENT parts (ptitle?, chapter+)>
<!ELEMENT ptitle (#PCDATA)>
<!ATTLIST parts pid ID #REQUIRED>

<!ELEMENT chapter (CHtitle?, summary?,sections+)>
<!ATTLIST chapter chid ID #REQUIRED>
<!ELEMENT CHtitle (#PCDATA)>
<!ATTLIST CHtitle length CDATA "2">
<!ELEMENT summary (#PCDATA)>
<!ATTLIST summary totalwords CDATA "10">
<!ELEMENT sections (content?)>
<!ELEMENT content (#PCDATA)>

=== AliFathy-1999/ITI-Tasks/XML Tasks/AliAhmed_XML_Lab1/src/main/java/aliahmed_xml_lab1/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->
<!DOCTYPE library SYSTEM "libraryDTD.dtd">

<library>
    <info>
        <location></location>
        <description></description>
        <librarian></librarian>
    </info>
    <books>
        <Btitle bid="a"></Btitle>
        <ISBN id="a"></ISBN>
        <Author gender="Male"></Author>
        <preface></preface>
        <parts pid="a">
            <ptitle>part 1</ptitle>
            <chapter chid="a">
                <CHtitle length="20"></CHtitle>
                <summary totalwords="30"></summary>
                <sections sid="a1">
                    <content>
                        <![CDATA[ 
Lorem ipsum dolor sit amet consectetur adipiscing elit proin nisi, natoque torquent diam class porta volutpat placerat.
                        ]]>
                    </content>
                </sections>
            </chapter>
        </parts>
    </books>
</library>
