=== AliFathy-1999/ITI-Tasks/XML Tasks/AliAhmed_XML_Lab2/src/main/java/task2/assig1Schema.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="library">
        <xs:complexType> 
            <xs:sequence>
                <xs:element name="librarian" type="xs:string" />
                <xs:element name="description" type="xs:string" />
                <xs:element name="location" type="xs:string" />
                <xs:element name="books" type="booksType" />
            </xs:sequence>    
        </xs:complexType>
    </xs:element> 
        <xs:complexType name="booksType"> 
            <xs:sequence> 
                <xs:element name="Btitle">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="bid" type="xs:positiveInteger" />
                            </xs:extension>
                        </xs:simpleContent> 
                    </xs:complexType>
                </xs:element>
                <xs:element name="ISBN" type="xs:positiveInteger"/>
                <xs:element name="Author">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="gender" type="genderType" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="preface" type="xs:string"/>
                <xs:element name="parts" type="partsType"/>
            </xs:sequence>     
            <xs:attribute name="bid" type="xs:positiveInteger"/>   
        </xs:complexType>     
        <xs:complexType name="partsType"> 
            <xs:sequence> 
                <xs:element name="ptitle" type="xs:string"/>
                <xs:element name="chapter" type="chaptersType"/>
            </xs:sequence>  
            <xs:attribute name="pid" type="xs:positiveInteger"/>   
        </xs:complexType> 
           <xs:complexType name="chaptersType"> 
                <xs:sequence> 
                    <xs:element name="CHtitle" type="xs:string"/>
                    <xs:element name="summary" type="xs:string"/>
                    <xs:element name="sections" type="sectionsType"/>  
                </xs:sequence>     
                
        </xs:complexType>
            <xs:complexType name="sectionsType"> 
                <xs:sequence> 
                    <xs:element name="content" type="xs:string"/>
                </xs:sequence>  
                <xs:attribute name="sid" type="xs:positiveInteger"/>   
        </xs:complexType> 
        <xs:simpleType name="genderType">
            <xs:restriction base="xs:string">
                <xs:enumeration value="Male"/>
                <xs:enumeration value="Female"/>
            </xs:restriction>
    </xs:simpleType> 
</xs:schema>

=== AliFathy-1999/ITI-Tasks/XML Tasks/AliAhmed_XML_Lab2/src/main/java/task2/assignment1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="assig1Schema.xsd">
        <librarian>ali</librarian>  
        <description>desc</description>  
        <location>location</location>
        <books>
            <Btitle bid="1">ITI</Btitle>
            <ISBN>22</ISBN>
            <Author gender="Male">Ali ahmed</Author>
            <preface>Welcome to ITI</preface>
            <parts pid="1">
                <ptitle>part 1</ptitle>
                <chapter>
                    <CHtitle> Chapter one</CHtitle>
                    <summary> Summary</summary>
                    <sections sid="1">
                        <content>content content</content>
                    </sections>
                </chapter>
            </parts>
        </books>
</library>
